version: "3"

volumes:
  web-media:
  web-static:

services:
  web:
    image: habit:latest
    volumes:
      - .:/app
      - web-static:/app/staticfiles
      - web-media:/app/media
      - ./media/logs:/app/media/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
